api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

from api import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'group', views.GroupViewSet)
router.register(r'product', views.ProductViewSet)
router.register(r'category', views.CategoryViewSet)
router.register(r'order', views.OrderViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from lib.views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^product-autocomplete/$', ProductAutocomplete.as_view(), name='product-autocomplete'),
    url(r'^category-autocomplete/$', CategoryAutocomplete.as_view(), name='category-autocomplete'),
    url(r'^categoryAll-autocomplete/$', CategoryAllAutocomplete.as_view(), name='categoryAll-autocomplete'),
    url(r'^supplier-autocomplete/$', SupplierAutocomplete.as_view(), name='supplier-autocomplete'),
    url(r'^item-autocomplete/$', ItemAutocomplete.as_view(), name='item-autocomplete'),
    url(r'^depot-autocomplete/$', DepotAutocomplete.as_view(), name='depot-autocomplete'),
    url(r'^channel-autocomplete/$', ChannelAutocomplete.as_view(), name='channel-autocomplete'),
    url(r'^itUser-autocomplete/$', ItUserAutocomplete.as_view(), name='itUser-autocomplete'),

    url(r'^productUser-autocomplete/$', ProductUserAutocomplete.as_view(), name='productUser-autocomplete'),
    url(r'^purchaseUser-autocomplete/$', PurchaseUserAutocomplete.as_view(), name='purchaseUser-autocomplete'),
    url(r'^depotUser-autocomplete/$', DepotUserAutocomplete.as_view(), name='depotUser-autocomplete'),
    url(r'^channelUser-autocomplete/$', ChannelUserAutocomplete.as_view(), name='channelUser-autocomplete'),
    url(r'^supplierUser-autocomplete/$', SupplierUserAutocomplete.as_view(), name='supplierUser-autocomplete'),
    url(r'^forSupplier-autocomplete/$', ForSupplierAutocomplete.as_view(), name='forSupplier-autocomplete'),#ForSupplierSupplierProductInline

    url(r'^purchaseOrder-autocomplete/$', PurchaseOrderAutocomplete.as_view(), name='purchaseOrder-autocomplete'),
    url(r'^purchaseOrderItem-autocomplete/$', PurchaseOrderItemAutocomplete.as_view(), name='purchaseOrderItem-autocomplete'),
    # url(r'^productRequestName-autocomplete/$', ProductRequestNameAutocomplete.as_view(), name='productRequestName-autocomplete'),
    url(r'^product/', include('product.urls')),
    url(r'^supply/', include('supply.urls')),
    url(r'^pick/', include('shipping.urls')),
    url(r'^tongguan/', include('tongguan.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^fba/', include('fba.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^depot/', include('depot.urls')),
    url(r'^order/', include('order.urls')),
]

shipping/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

from shipping import views

urlpatterns = [
    # 拣货页面
    url(r'^index/$', views.index, name='pick_index'),
    url(r'^list/(?P<pick_parm>[^/]*)/$', views.pick_list, name='pick_list'),
    url(r'^assign_shipping/(?P<assign_parm>[^/]*)/$', views.assign_shipping, name='assign_shipping'),
    url(r'^get_tracking_no/$', views.get_tracking_no, name='get_tracking_no'),
    url(r'^create/$', views.pick_create, name='pick_create'),
    url(r'^sort/$', views.pick_sort, name='pick_sort'),
    url(r'^packaging/$', views.pick_packaging, name='pick_packaging'),
    url(r'^print_label/$', views.print_label, name='print_label'),
    url(r'^ajax_sort/$', views.ajax_sort, name='ajax_sort'),
    url(r'^abnormal/$', views.pick_abnormal, name='pick_abnormal'),
    url(r'^re_print/$', views.pick_re_print, name='pick_re_print'),
    url(r'^manual_deliver/$', views.manual_deliver, name='pick_manual_deliver'),
    url(r'^execute_deliver/(?P<status>[^/]*)/$', views.execute_deliver, name='pick_execute_deliver'),
    url(r'^assign/$', views.assign_assigner, name='pick_assign_assigner'),
    
]

shipping/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db.models import Sum

import lib
import order
import product
import depot
import supply

class Package(models.Model):

    STATUS = (
        (0, u'未处理'),
        (1, u'开始处理'),#手动审核
        (2, u'配货中'),#开始pick，全部用库存
        (3, u'打包中'),
        (5, u'已发货'),
        (6, u'妥投'),
        (7, u'到达待取'),
        (4, u'取消'),
    )

    PICK_STATUS = (
        (0, u'未分拣'),
        (1, u'分拣中'),
        (2, u'分拣完成'),
        (3, u'包装完成'),
        (4, u'分拣异常'),
        (5, u'包装异常'),
    )

    order = models.ForeignKey('order.Order', verbose_name=u'订单')#与订单表中import 冲突
    status = models.IntegerField(choices=STATUS, default=0, verbose_name=u'包裹发货状态')
    shipping = models.ForeignKey(lib.models.Shipping, null=True, blank=True, verbose_name=u'物流方式')
    note = models.TextField(default='', blank=True, null=True, verbose_name=u'备注')

    tracking_no = models.CharField(max_length=250, default="", blank=True, db_index=True, verbose_name=u'运单号')
    ship_time = models.DateTimeField(blank=True, null=True, verbose_name=u'执行发货时间')
    shipper = models.ForeignKey(User, null=True, blank=True, related_name="package_shipper", verbose_name=u'执行发货人') #执行发货人
    print_time = models.DateTimeField(blank=True, null=True, verbose_name=u'包裹打印时间')
    printer = models.ForeignKey(User, null=True, blank=True, related_name="package_printer", verbose_name=u'打印包裹/面单人') #打印面单人

    email = models.EmailField(default='', verbose_name=u'收件人邮箱')
    shipping_firstname = models.CharField(u'收件人姓', max_length=100, default='', blank=True, null=True)
    shipping_lastname = models.CharField(u'收件人名', max_length=100, default='', blank=True, null=True)
    shipping_address = models.CharField(u'收件人地址', max_length=500, default='', blank=True, null=True)
    shipping_address1 = models.CharField(u'收件人地址1', max_length=500, default='', blank=True, null=True)
    shipping_city = models.CharField(u'收件人城市', max_length=250, default='', blank=True, null=True)
    shipping_state = models.CharField(u'收件人州', max_length=250, default='', blank=True, null=True)

    shipping_country = models.ForeignKey(lib.models.Country, null=True, blank=True)
    shipping_zipcode = models.CharField(u'收件人邮编', max_length=100, default='', blank=True, null=True)
    shipping_phone = models.CharField(u'收件人电话', max_length=100, default='', blank=True, null=True)

    qty = models.IntegerField(default=0, blank=True, verbose_name=u"货品总数")
    sku_qty = models.IntegerField(default=0, blank=True, verbose_name=u"SKU总数")
    weight = models.FloatField(u'包裹重量', default=0.0)
    cost = models.FloatField(default=0, blank=True, null=True, verbose_name=u"成本")
    cost1 = models.FloatField(default=0, blank=True, null=True, verbose_name=u"成本1")

    sf_numbers = models.CharField(u"顺丰单号", max_length=30, default="", blank=True)
    skybill_code = models.CharField(u"顺丰渠道转单号", max_length=30, default="", blank=True)

    pick = models.ForeignKey(depot.models.Pick, null=True, blank=True, verbose_name=u"拣货单")
    pick_type = models.IntegerField(u'拣货单类型', choices=depot.models.Pick.PICK_TYPES, default=0)
    pick_status = models.IntegerField(u'分拣状态', choices=PICK_STATUS, default=0, blank=True)
    code = models.IntegerField(u'是否同一物理仓，一起拣货', choices=depot.models.Depot.CODE, default=0)
    position_score = models.IntegerField(default=0, blank=True, verbose_name=u'库位得分')
    pick_error_info = models.TextField(default='', blank=True, verbose_name=u'拣货单异常信息')

    option_log = models.TextField(default='', blank=True, verbose_name=u'操作记录')

    created = models.DateTimeField(auto_now_add=True, verbose_name=u"新建时间")
    updated = models.DateTimeField(auto_now=True, verbose_name=u"修改时间")

    _status = None

    class Meta:
        verbose_name = u'包裹单'
        verbose_name_plural = u'包裹单'

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model), args=(self.id,))

    def __unicode__(self):
        return "PACKAGE#%s" % self.id

    def __init__(self, *args, **kwargs):
        super(Package, self).__init__(*args, **kwargs)
        self._status = self.status
        self._shipping_id = self.shipping_id
        self._tracking_no = self.tracking_no

    def can_pick(self):
        can_pick = False
        packageitems = PackageItem.objects.filter(package=self).filter(deleted=False)
        for packageitem in packageitems:
            can_pick = True
            qty_locked = ItemLocked.objects.filter(package_item=packageitem, deleted=False).aggregate(Sum('qty'))['qty__sum']
            if not qty_locked:
                qty_locked = 0

            if packageitem.qty != qty_locked:
                can_pick = False
                break

        return can_pick

    def get_name(self):
        return self.shipping_firstname + ' ' + self.shipping_lastname

    def get_address(self):
        return self.shipping_address + ' ' + self.shipping_address1

    def get_weight(self):
        weight = 0
        for item_weight, qty in self.packageitem_set.filter(deleted=False).values_list('item__product__weight', 'qty'):
            weight += item_weight * qty
        return weight

    def get_qty(self):
        qty = self.packageitem_set.filter(deleted=False).aggregate(Sum('qty')).get('qty__sum') or 0
        return qty 

    def get_sku_qty(self):
        qty = self.packageitem_set.filter(deleted=False).values('item_id').count() or 0
        return qty 

    def get_pick_type(self):
        """根据package的ItemLocked的数量来判断pick_type"""
        item_count = ItemLocked.objects.filter(package_item__package_id=self.id).filter(deleted=False).count()
        item_qtys = self.packageitem_set.aggregate(Sum('qty')).get('qty__sum') or 0

        if item_count == 1 and item_qtys == 1:
            pick_type = 1
        elif item_count == 1 and item_qtys > 1:
            pick_type = 2
        elif item_count > 1:
            pick_type = 3
        else:
            pick_type = 0
        return pick_type

    def get_position_score(self):
        """获取package的库位得分"""
        positions = ItemLocked.objects.filter(package_item__package_id=self.id)\
                                      .values_list('depot_item__position', flat=True)
        # todo 南京和广州库位排序, 和库位规则可能不同, 需要各自定义
        positions = [i.split(',')[0] for i in positions if i]
        # 每个库位只计算一次, 所以使用set推导式
        if self.code == 1:  # 南京
            SCORE_STR = "ABCDEFGHIJKLMNOPGRSTUVWXYZ"
            diff_str = {i[1] for i in positions}
        elif self.code == 2: # 广州
            SCORE_STR = "EFBDCAGHIJKLMNOPGRSTUVWXYZ"
            diff_str = {i[2] for i in positions}

        # 计算每个不同库位得分之和
        return sum([2**SCORE_STR.index(i) for i in diff_str])

    def get_custom_amount(self):
        '''计算package的通关打印金额, 这个金额根据各个渠道需求进行设置'''
        # todo add custom_amount字段
        if hasattr(self, 'custom_amount') and self.custom_amount:
            return self.custom_amount

        custom_amount = 0
        #shop为choies
        shop_type = self.order.channel.type
        if shop_type == 0:
            items = self.packageitem_set.values_list('item__product__category__name', 'qty')
            for category, qty in items:
                # todo shoes的category确定
                if category.lower() == 'shoes':
                    custom_amount += 15 * qty
                # todo 首饰的category的确定
                elif category.lower() in ['anklets', 'body chains', 'bracelets & bangles', 'earrings', 'necklaces', 'rings']:
                    custom_amount += 0.5 * qty
                else:
                    custom_amount += 5 * qty
        # todo 速卖通和wholesale的shop确认
        elif shop_type in (2, 8):
            custom_amount = self.get_qty() * 2
        if custom_amount >= 20 or custom_amount == 0:
            return 20
        else:
            return custom_amount

    def set_to_logistics(self):
        '''给物流api准备好package和packageitem的数据
        物流api一般只传递一个packageitem, 数量传递这个包裹中准确的数量'''
        self.name = self.get_name()
        self.qty = self.get_qty()
        self.weight = self.weight or self.get_weight()
        self.address = self.get_address()
        self.custom_amount = self.get_custom_amount()
        if self.qty:
            self.price = round(float(self.custom_amount) / self.qty, 2)
        else:
            self.price = 0

        packageitem = self.packageitem_set.first()
        if packageitem:
            packageitem.name, packageitem.cn_name = packageitem.get_item_name()
        return packageitem

    def have_nails(self):
        '''判断是否含有指甲油(发货的时候, 如果含有指甲油, 则需要手工发货)'''
        package_item_categorys = self.packageitem_set.values_list('item__product__category__name', flat=True)
        if 'nails' in [i.lower for i in package_item_categorys]:
            return True
        else:
            return False

    def get_carrier(self):
        '''根据指定规则, 获取当前package的carrier label, 如果没有合适的, 则返回空字符串'''
        carrier = ''

        amount_shipping = round(self.order.amount_shipping / self.order.rate, 2)
        shipping_country = self.shipping_country.code
        weight = self.get_weight()
        tongguan = True if not self.order.cannot_tongguan() else False

        if self.note or self.order.note:
            pass

        # ky即smt的物流方式
        elif self.order.channel.type == 2:
            # 港澳台, 国内
            if shipping_country in ['HK','MO','TW',"CN"]:
                carrier = 'SF'
            else:
                if amount_shipping >= 10 or self.order.shipping_type == 1:
                    # 阿联酋、印度、阿曼、孟加拉国
                    if shipping_country in ['AE', 'IN', 'OM', 'BD']:
                        carrier = 'ARAMEX'
                    else:

shipping/templates/get_tracking_no.html
{% extends "base_header.html" %}
{% block content %}


<form action="" method="post" target="_blank">
{% csrf_token %}
<div style="font-size:16px;">
{% for carrier, shippings in shipping_list.iteritems %}
    <div class="carrier_shipping" style="margin-bottom: 20px;">
        <label style="width:100px;font-weight:normal;">{{ carrier|title }}: </label>
        {% for data in shipping_counts %}
            {% if data.shipping__label in shippings %}
            <input type="checkbox" name="shipping_label" value="{{ data.shipping__label }}" id="shipping_{{ data.shipping__label }}">
            <label for="shipping_{{ data.shipping__label }}" style="width:170px;">{{ data.shipping__label }}物流商下单({{ data.id__count }})</label>
            {% endif %}
        {% endfor %}
    </div>
    
{% endfor %}
</div>
    <input class="btn btn-small btn-primary" type="submit" value="submit">
</form>
<br>

{% endblock %}

shipping/templates/sort.html
{% extends "base_header.html" %}
{% block content %}
<div class="loading"></div>

<form class="form-inline" id="pick_num_form" method="get">
    <label style="width:240px;">扫描/录入拣货单号开始多品分拣: </label>
    <input type="hidden" name="type" value="start_pick">
    {% if packages %}
    <span id="pick_num_span">
        <span style="width:300px;font-size:16px;margin-right:10px;">当前拣货单号: {{ pick.pick_num }} </span>
        <a href="javascript:;" id="reset_search">重新扫描拣货单</a>
    </span>
    <span id="pick_input_span" style="display:none;">
    {% else %}
    <span>
    {% endif %}
        <input type="text" class="form-control" name="pick_num" id="pick_num" value="" style="width:300px;">
        <input type="submit" class="btn btn-primary" value="submit">
    </span>
</form>

{% if picks and not packages %}
<br>
<table class="table-bordered">
    <thead>
        <tr>
            <th style="width:10%;">NO.</th>
            <th style="width:10%;">拣货单号</th>
            <th style="width:10%;">实体仓库</th>
            <th style="width:10%;">物流方式</th>
            <th style="width:10%;">拣货单类型</th>
            <th style="width:10%;">拣货单状态</th>
            <th style="width:15%;">操作</th>
        </tr>
    </thead>
    <tbody>
        {% for pick in picks %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ pick.pick_num }}</td>
            <td>{{ pick.get_code_display }}</td>
            <td>{{ pick.shipping }}</td>
            <td>{{ pick.get_pick_type_display }}</td>
            <td>{{ pick.get_status_display }}</td>
            <td>
            {% if pick.pick_type == 3 and pick.status == 1 %}
                <a href="{% url 'pick_sort' %}?type=cancel_sort&pick_num={{ pick.pick_num }}" class="btn btn-xs btn-info cancel_sort" style="color:#fff;">撤销分拣</a>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>                  
</table>
{% endif %}

{% if packages %}
<form class="form-inline" id="sku_form">
    <label style="width:240px;">扫描单品SKU开始包装: </label>
    <input type="text" class="form-control" name="sku" id="sku" style="width:300px;">
    <input type="submit" class="btn btn-primary" value="submit">
</form>
    
{% if pick.pick_type == 3 %}
<br>
<div id="search_table" style='margin-left:50px;'>
    <table class="table-bordered" style="text-align:center;">
        <tr>
            <td style="font-size:30px;font-weight:bolder;vertical-align:middle;width:400;height:50;">SKU</td>
            <td style="font-size:30px;font-weight:bolder;vertical-align:middle;width:300;">分拣区号</td>
            <td style="font-size:30px;font-weight:bolder;vertical-align:middle;width:300;">图片</td>
        </tr>
        <tr>
            <td id="search_sku"  style="font-size:30px;font-weight:bolder;vertical-align:middle;height:180;"</td>
            <td id="search_area" style="font-size:99px;font-weight:bolder;vertical-align:middle;color:green;"></td>
            <td id="search_img"  ></td>
        </tr>
    </table>
    <div id="search_index" style="display:none;"></div>
</div>
{% endif %}


<div style="margin:30px 10px;width:90%;" id="pick_div">
    <table class="table-bordered">
        <thead>
            <tr>
                <th width="4%">NO.</th>
                <th width="8%">拣货单号</th>
                <th width="8%">Package Id</th>
                <th width="8%">物流方式</th>
                <th width="10%">追踪号</th>
                <th width="8%">Shop</th>
                <th width="15%">Note</th>
                <th width="15%">SKU(点击复制到输入框)</th>
                <th width="8%">总数量</th>
                <th width="8%">已分拣数量</th>
                <th width="8%">状态</th>
            </tr>
        </thead>
        <tbody id="pick_data">
            {% for package in packages %}
                {% for item in package.items %}
                <tr {% if forloop.parentloop.counter|divisibleby:2 %} class="background-double"{% endif %}>
                    {% if forloop.first %}
                        <td rowspan="{{ forloop.revcounter }}">{{forloop.parentloop.counter}}<span id="pick_package_{{ forloop.parentloop.counter }}" style="display:none;">{{ package.index }}</span></td>
                        <td rowspan="{{ forloop.revcounter }}">{{ pick.pick_num }}</td>
                        <td rowspan="{{ forloop.revcounter }}" id="package_{{ forloop.parentloop.counter }}" class="package_id">{{ package.id }}</td>
                        <td rowspan="{{ forloop.revcounter }}" class="ship_type">{{ pick.shipping }}</td>
                        <td rowspan="{{ forloop.revcounter }}" id="tracking_no_{{ forloop.parentloop.counter }}" class="tracking_no">{{ package.tracking_no }}</td>
                        <td rowspan="{{ forloop.revcounter }}" id="shop_{{ forloop.parentloop.counter }}" >{{ package.shop }}</td>
                        <td rowspan="{{ forloop.revcounter }}" id="note_{{ forloop.parentloop.counter }}">{{ package.package_note }}|{{ package.order_note }}</td>
                    {% endif %}
                    <td class="pick_sku" id="pick_sku_{{ item.id }}">
                        <span class="btn btn-xs btn-info copy_sku">{{ item.sku }}</span>
                        {% if item.choies_sku %}
                            <br> <span class="btn btn-xs btn-default copy_sku">{{ item.choies_sku }}</span>
                        {% endif %}
                    </td>
                    <td class="item_qty" id="item_qty_{{ item.id }}">{{ item.qty }}</td>
                    <td class="pick_qty" id="pick_qty_{{ item.id }}">{{ item.pick_qty }}</td>
                    {% if forloop.first %}
                        <td rowspan="{{ forloop.revcounter }}" class="package_status" id="package_status_{{ package.id }}">
                            {% if package.pick_status == 3 or package.pick_status == 2 %} √ {% endif %}
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    <div style="margin-bottom:20px;float:right;">
        <form action="" method="post" id="finish_pick" onsubmit="return finish_pick();">
            <a href="javascript:" class="btn btn-default finish_pick">
            {% if pick.pick_type == 3 %}
                分拣完成
            {% else %}
                包装完成
            {% endif %}
            </a>
        </form>
    </div>
</div>
{% endif %}

<div id="check_div" style="float: left; width: 450px; box-shadow: 0px 0px 8px rgb(94, 94, 94); padding: 10px; margin: 200px 0px 0px 20px; border: 5px solid rgb(163, 164, 165); position: fixed; background: rgb(255, 255, 255) none repeat scroll 0% 0%; left: 30%; top: 50px; display: none;">
    <div>
        <span style="font-size:15px;">提示</span>
    </div>
    <hr size="1">
    <div style="margin:10px 30px 20px 30px;text-align:center;font-size:16px;" id="pick_msg"></div>
    <hr size="1">
    <div style="text-align:center;margin-bottom:20px;">
        <br>
        <button id="check_close" class="btn btn-info" href="javascript:;">我知道了</button>
    </div>
</div>

<div id="audio" style="display:none">
    <audio id="player" src="/static/audio/warning.wav">
</div>

<iframe id="print_iframe" src="" style="display:none;"></iframe>

<script type="text/javascript">
    $(document).ready(function(){
        // sku获得焦点时的事件
        $("#sku").focus(function(){
            $("#sku").select();
        })

        // 复制sku到输入框
        $(".copy_sku").each(function(){
            $(this).click(function(){
                $("#sku").val($(this).text());
                $("#sku").focus();
            });
        })

        // 设置弹出框
        $("#check_close").click(function(){
            $("#check_div").hide();
            $("#sku").focus();
        })

        // 设置不同package的背景色
        $(".background-double").css('background-color', '#F5F5F5');

        // 重设搜索拣货单的输入框
        $("#reset_search").click(function(){
            $("#pick_num_span").hide();
            $("#pick_input_span").show();
            return false;
        });

        // 分拣方法
        $("#sku_form").submit(function(){

            $(".loading").show();
            var sku = $("#sku").val();
            var pick_type = {{ pick.pick_type }}

            $.ajax({
                type: "POST",
                url: "{% url 'ajax_sort' %}",
                dataType: "json",
                async : false,
                data: {
                    "type": "sort",
                    "pick_type": pick_type,
                    "pick_num": "{{ pick.pick_num }}",
                    "sku": sku,
                },
                success: function(res){
                    if(!res['success']){
                        $("#pick_msg").html(res['msg']);
                        $("#check_div").show(function(){
                            $("#player")[0].play()
                        });
                        $("#check_div").focus();
                    }else{
                        $("#search_sku").html(res['packageitem']['sku'] + "<br><br> (" + res['packageitem']['choies_sku'] + ")");
                        // $("#search_img").html('<img width="200" src="' + res['packageitem']['img'] + '">'); // todo
                        $("#search_area").html(res['package']['index']);

                        var packageitem_id = res['packageitem']['id'];

                        $("#pick_qty_" + packageitem_id).text(res['packageitem']['pick_qty'])

                        // 当package的单单或单多的时候, 进行面单的打印
                        if((pick_type == 1 || pick_type == 2) && res['packageitem']['status'] == 1){
                            var iframe_src = '/pick/print_label?pick_type={{ pick.pick_type }}' + '&package_list=' + res['package']['id'];
                            $("#print_iframe").attr('src', iframe_src);
                            $("#print_iframe").load(function(){
                                $("#print_iframe")[0].contentWindow.focus();
                                $("#print_iframe")[0].contentWindow.print();
                            });
                        }

                        // 打印完成之后, 再进行package的状态更新
                        result = update_package_status(res['package']['id'])

                        // 当package为分拣完成或者包装完成的时候, 状态为ok
                        if(result['package']['pick_status'] == 2 || result['package']['pick_status'] == 3){
                            $("#package_status_"+result['package']['id']).text('√');
                        }

                        // 重新定位回sku
                        $("#sku").focus();
                    }
                }

            });
            return false;
        });
        
        // 分拣完成按钮
        $('.finish_pick').click(function(){
            if(!can_finish()){
                if(!confirm('还有包裹没有分拣完毕,确定要完成拣货单么?')){
                    return false;
                }
            }
            // can_finish和confirm都finish_pick
            finish_pick();
        });

    });

    function update_package_status(package_id){
        result = true;
        $.ajax({
            type: 'POST',
            url: "{% url 'pick_sort' %}",
            dataType: "json",
            async : false,
            data: {
                "type": "update_package_status",
                "pick_num": "{{ pick.pick_num }}",
                "package_id": package_id,
            },
            success: function(res){
                result = res;
            }
        });
        return result;
    }
    

    function can_finish(){
        result = true;
        $.ajax({
            type: 'POST',
            url: "{% url 'pick_sort' %}",
            dataType: "json",
            async : false,
            data: {
                "type": "can_finish",
                "pick_num": "{{ pick.pick_num }}",
            },
            success: function(res){
                result = res['success'];
            }
        });
        return result;
    }


    function finish_pick(){
        $.ajax({
            type: 'POST',
            url: "{% url 'pick_sort' %}",
            dataType: "json",
            async : false,
            data: {
                "type": "finish_pick",
                "pick_num": "{{ pick.pick_num }}",
            },
            success: function(res){
                var message = '拣货单已标记为已完成';
                $("#pick_msg").html(message);
                $("#check_div").show();
                $("#check_close").focus();
                location.href=res['path'];
            }
        })
    }

    function open_single_link(ship_type, package_id){
        $.ajax({
            type: 'POST',
            url: "/pick/ajax_process",
            dataType: "json",
            // data: "type=get_single_link&ship_type=" + ship_type + "&package_id=" + package_id,
            data: {
                "type": "get_single_link",
                "ship_type": "ship_type",
                "package_id": "package_id",
            },
            success: function(res){
                if(res['success'])
                {
                    $("#sku").focus();
                    window.open(res['single_link']);
                }
                else
                {
                    alert(res['msg']);
                }
            }
        })
    }
</script>
{% endblock %}