api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

from api import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'group', views.GroupViewSet)
router.register(r'product', views.ProductViewSet)
router.register(r'category', views.CategoryViewSet)
router.register(r'order', views.OrderViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from lib.views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^product-autocomplete/$', ProductAutocomplete.as_view(), name='product-autocomplete'),
    url(r'^category-autocomplete/$', CategoryAutocomplete.as_view(), name='category-autocomplete'),
    url(r'^categoryAll-autocomplete/$', CategoryAllAutocomplete.as_view(), name='categoryAll-autocomplete'),
    url(r'^supplier-autocomplete/$', SupplierAutocomplete.as_view(), name='supplier-autocomplete'),
    url(r'^item-autocomplete/$', ItemAutocomplete.as_view(), name='item-autocomplete'),
    url(r'^depot-autocomplete/$', DepotAutocomplete.as_view(), name='depot-autocomplete'),
    url(r'^channel-autocomplete/$', ChannelAutocomplete.as_view(), name='channel-autocomplete'),
    url(r'^itUser-autocomplete/$', ItUserAutocomplete.as_view(), name='itUser-autocomplete'),

    url(r'^productUser-autocomplete/$', ProductUserAutocomplete.as_view(), name='productUser-autocomplete'),
    url(r'^purchaseUser-autocomplete/$', PurchaseUserAutocomplete.as_view(), name='purchaseUser-autocomplete'),
    url(r'^depotUser-autocomplete/$', DepotUserAutocomplete.as_view(), name='depotUser-autocomplete'),
    url(r'^channelUser-autocomplete/$', ChannelUserAutocomplete.as_view(), name='channelUser-autocomplete'),
    url(r'^supplierUser-autocomplete/$', SupplierUserAutocomplete.as_view(), name='supplierUser-autocomplete'),
    url(r'^forSupplier-autocomplete/$', ForSupplierAutocomplete.as_view(), name='forSupplier-autocomplete'),#ForSupplierSupplierProductInline

    url(r'^purchaseOrder-autocomplete/$', PurchaseOrderAutocomplete.as_view(), name='purchaseOrder-autocomplete'),
    url(r'^purchaseOrderItem-autocomplete/$', PurchaseOrderItemAutocomplete.as_view(), name='purchaseOrderItem-autocomplete'),
    # url(r'^productRequestName-autocomplete/$', ProductRequestNameAutocomplete.as_view(), name='productRequestName-autocomplete'),
    url(r'^product/', include('product.urls')),
    url(r'^supply/', include('supply.urls')),
    url(r'^pick/', include('shipping.urls')),
    url(r'^tongguan/', include('tongguan.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^fba/', include('fba.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^depot/', include('depot.urls')),
    url(r'^order/', include('order.urls')),
]

supply/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

from supply import views

urlpatterns = [
    #供应商管理

    url(r'^supplier/add/$', views.SupplierEdit.as_view(),{'id':0,'flag':'add'}, name='supplier_add',),
    url(r'^supplier/edit/(?P<id>\d+)/$', views.SupplierEdit.as_view(),{'flag':'edit'}, name='supplier_edit'),
    url(r'^supplier/list/$', views.supplier_list, name='supplier_list'),
    url(r'^supplier/delete/$', views.supplier_delete, name='supplier_delete'),

    url(r'^supplier/ajax_item_weight', views.ajax_item_weight, name='ajax_item_weight'),
    url(r'^supplier/ajax_update_poi_trackingNo', views.ajax_update_poi_trackingNo, name='ajax_update_poi_trackingNo'),
    url(r'^supplier/ajax_update_checkorder_num', views.ajax_update_checkorder_num, name='ajax_update_checkorder_num'),

    url(r'^create_purchaseorder/$', views.create_purchaseorder, name='create_purchaseorder'),
    #
    # #供应商角色
    # # url(r'^supplier/info/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^supplier/publish/list/$', views.supplier_delete, name='supplier_delete'),#供应商下架产品
    # url(r'^supplier/publish/add/$', views.supplier_delete, name='supplier_delete'),#供应商发布产品
    # url(r'^supplier/purchaseorder/$', views.supplier_delete, name='supplier_delete'),#供应商被指定的采购单列表
    # url(r'^supplier/publish/delete/$', views.supplier_delete, name='supplier_delete'),#供应商下架产品,删除绑定记录
    #
    # #采购需求
    # url(r'^purchase/need/list/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/need/add/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/need/edit/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/need/delete/$', views.supplier_delete, name='supplier_delete'),#批量删除
    #
    # #采购单
    # url(r'^purchase/order/list/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/order/add/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/order/edit/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/order/delete/$', views.supplier_delete, name='supplier_delete'),#批量删除
    # url(r'^purchase/item/list/$', views.supplier_delete, name='supplier_delete'),
    # url(r'^purchase/item/edit/$', views.supplier_delete, name='supplier_delete'),






]

supply/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from mptt.models import MPTTModel
import datetime
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse

import os
import product
import order
import depot
import lib
import uuid
from django.db.models import Sum


class ProductForSupplier(product.models.Product):

    def save(self, *args, **kwargs):
        self.status = 0
        super(ProductForSupplier, self).save(*args, **kwargs)

    class Meta:
        proxy = True
        verbose_name = u'供应商产品'
        verbose_name_plural = u'供应商产品'

class Supplier(models.Model):

    TYPE = (
        (0, u'线下'),
        (1, u'线上'),
        (2, u'工厂'),
    )
    SUPPLY_CLASS = (
        (0, u'A'),
        (1, u'B'),
        (2, u'C'),
        (3, u'D'),
    )

    STATUS = (
        (0, u'未审核'),
        (1, u'已审核'),
        (2, u'关闭'),
    )

    PURCHASE_WAY = (
        (0, u'零采'),
        (1, u'备货/囤货'),
        (2, u'做货'),
    )

    name = models.CharField(max_length=250, verbose_name=u"供应商名称")
    type = models.IntegerField(choices=TYPE, default=0, verbose_name=u"类型")
    site = models.CharField(max_length=250, blank=True, verbose_name=u"供应商访问网址")
    phone = models.CharField(max_length=250, blank=True, default="", verbose_name=u"电话")
    address = models.TextField(default="", blank=True, verbose_name=u"地址")
    note = models.TextField(default="", blank=True, verbose_name=u"备注")
    manager = models.ForeignKey(User, null=True,  verbose_name=u"负责人")
    products = models.ManyToManyField(product.models.Product, blank=True, through='supply.SupplierProduct', verbose_name=u"供应商产品")

    created = models.DateTimeField(auto_now_add=True, verbose_name=u"新增时间")
    updated = models.DateTimeField(auto_now=True, verbose_name=u"修改时间")
    deleted = models.BooleanField(default=False, verbose_name=u"是否已删除")
    #新增字段
    supplier_class = models.IntegerField(choices=SUPPLY_CLASS, default=0,  verbose_name=u"供应商等级")
    payment_information = models.TextField(default="", blank=True, verbose_name=u"付款资料")
    tax_id = models.CharField(max_length=100, blank=True, verbose_name=u"税务登记号")
    status = models.IntegerField(choices=STATUS, default=0, verbose_name=u"供应商状态")
    purchase_way = models.IntegerField(choices=PURCHASE_WAY, default=0, verbose_name=u"采购方式")
    category = models.ManyToManyField(product.models.Category,blank=True, verbose_name=u"供应商供应的产品分类", help_text=u"供应商供应的产品分类")
    login_user = models.ForeignKey(User, blank=True, null=True, verbose_name=u"系统登录用户", related_name='supplier_login_user', help_text=u"系统登录用户")


    class Meta(object):
        verbose_name = u'供应商'
        verbose_name_plural = u'供应商'

    def __unicode__(self):
        return "%03d.%s" % (self.id, self.name)

    def supplier_list(self,search,userid):
        if not search:
            return Supplier.objects.filter(deleted=0,manager_id=userid).order_by('id')
        else:
            return Supplier.objects.filter(deleted=0,name__contains=search,manager_id=userid).order_by('id')

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model), args=(self.id,))

class SupplyImage(models.Model):
    image = models.ImageField(upload_to=product.models.get_product_image_upload_path, verbose_name=u"图片地址")#此处存储图片的规则和产品图片一致，方法直接引用产品图片
    supplier = models.ForeignKey(Supplier, verbose_name=u"供应商名称")

   #img_updater = models.ForeignKey(User, related_name='img_updater', verbose_name=u"修改图片人员")
    img_adder = models.ForeignKey(User, related_name='img_adder', verbose_name=u"新增图片人员")
    created = models.DateTimeField(auto_now_add=True, verbose_name=u"新增时间")
    updated = models.DateTimeField(auto_now=True, verbose_name=u"修改时间")
    deleted = models.BooleanField(default=False, verbose_name=u"是否已删除")

    class Meta:
        verbose_name = u'供应商三证合一图片'
        verbose_name_plural = u'供应商三证合一图片'

    def __unicode__(self):
        return 'SupplyImage %s' % self.id


class SupplierProduct(models.Model):

    supplier = models.ForeignKey(Supplier, verbose_name=u"供应商名称")
    product = models.ForeignKey(product.models.Product, verbose_name=u"产品名称")
    order = models.PositiveIntegerField(default=1, verbose_name=u"产品绑定的供应商优先级")

    created = models.DateTimeField(auto_now_add=True,verbose_name=u"新增时间")
    updated = models.DateTimeField(auto_now=True, verbose_name=u"修改时间")
    deleted = models.BooleanField(default=False, verbose_name=u"是否已删除")
    # 新增字段
    # purchase_way = models.IntegerField(choices=PURCHASE_WAY, default=0, verbose_name=u"采购方式")#此字段移动到供应商表中
    supplier_period = models.IntegerField(default=0, verbose_name=u"供货周期")
    supplier_cost = models.FloatField(default=0.0, verbose_name=u"供货成本")
    supplier_min_qty = models.IntegerField(default=1, verbose_name=u"起订量")
    supplier_sku = models.CharField(max_length=200, verbose_name="供应商SKU", default='', blank=True)
    supplier_inventory = models.IntegerField(default=0,blank=True, verbose_name=u"供应商的参考库存")
    supplier_shipping_fee = models.FloatField(default=0.0,blank=True, verbose_name=u"物流费用")
    site_url = models.CharField(max_length=250, blank=True, verbose_name=u"供应商产品访问网址")

    class Meta:
        verbose_name = u'供应商产品'
        verbose_name_plural = u'供应商产品'

    def __unicode__(self):
        return "SUPPLYPRODUCT:%s" % self.id

class PurchaseOrder(models.Model):

    PURCHASE_STATUS = (
            (0, u'未处理'),
            (1, u'开始采购'),
            (2, u'完全入库'),
            (3, u'部分入库'),
            (4, u'取消'),
            )
# 暂时没有用，去掉
#     PURCHASE_ACTIVE = (
#             (0, u'未处理'),
#             (1, u'开始采购'),
#             (2, u'完全入库'),
#             (3, u'部分入库'),
#             (4, u'取消'),
#     )

    PURCHASE_CLOSE_STATUS= (
            (0, u'未结算'),
            (1, u'已结算'),
            (2, u'不参与结算'),
            )

    PURCHASE_TYPE = (
        (0, u'零采'),
        (1, u'样品采'),
        (2, u'做货'),
        (3, u'移库'),
    )
    # supplier = models.ForeignKey(Supplier, null=True, blank=True, verbose_name=u"供应商名称")
    supplier = models.ForeignKey(Supplier, verbose_name=u"供应商名称")#供应商不可以为空
    status = models.IntegerField(choices=PURCHASE_STATUS, default=0, verbose_name=u"采购单状态")
    close_status = models.IntegerField(choices=PURCHASE_CLOSE_STATUS, default=0, verbose_name=u"是否已结算")
    total = models.FloatField(default=0, blank=True, null=True, verbose_name=u"采购总成本")
    # active = models.IntegerField(choices=PURCHASE_ACTIVE, default=0, verbose_name=u"采购状态")
    note = models.TextField(default='', blank=True, null=True, verbose_name=u"备注")
    manager = models.ForeignKey(User, null=True, blank=True, verbose_name=u"采购人员")
    # shipping = models.ForeignKey(lib.models.Shipping, blank=True, null=True,default=None)没有用，指向的国际物流方式
    tracking = models.TextField(default='', blank=True, null=True, verbose_name=u"运单号")
    #is_forecast = models.BooleanField('是否囤货 ?', default=False)

    #选择"FBA采购"为True时，"渠道"必需填
    is_fba = models.BooleanField(default=False, verbose_name="FBA采购")
    channel = models.IntegerField(default=0, verbose_name=u"渠道")
    shipping_fee = models.FloatField(default=0, blank=True, null=True, verbose_name=u"采购单运费")

    creater = models.ForeignKey(User, null=True, blank=True, related_name="creater", verbose_name=u"录入单据人员")

    created = models.DateTimeField(auto_now_add=True, verbose_name=u"新增时间")
    updated = models.DateTimeField(auto_now=True, verbose_name=u"修改时间")
    deleted = models.BooleanField(default=False, verbose_name=u"是否已删除")

    updater = models.ForeignKey(User, null=True, blank=True,related_name="updater", verbose_name=u"修改人员")
    depot = models.ForeignKey(depot.models.Depot, verbose_name=u"采购入库仓库")
    type = models.IntegerField(choices=PURCHASE_TYPE, default=0, verbose_name=u"采购类型")
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name=u"主单")

    _status = None

    class Meta:
        verbose_name = u'采购单'
        verbose_name_plural = u'采购单'

    def __unicode__(self):
        return u"PURCHASE#%s" % self.id

    def __init__(self, *args, **kwargs):
        super(PurchaseOrder, self).__init__(*args, **kwargs)
        self._status = self.status

    def save(self, *args, **kwargs):
        super(PurchaseOrder, self).save(*args, **kwargs)
        if self.status==4:
            PurchaseOrderItem.objects.filter(purchaseorder_id=self.id).update(status=0)
        if self.type == 2:
            MadeOrder.objects.get_or_create(purchaseorder=self)

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model), args=(self.id,))

class PurchaseOrderItem(models.Model):

    ACTION_STATUS = (
            (0, u'未处理'),
            (1, u'部分对单'),
            (2, u'全部对单'),
            )

    IN_STATUS = (
            (0, u'未处理'),
            (1, u'部分入库'),
            (2, u'完全入库'),
            )

    STATUS = (
            (1, u'正常'),
            (2, u'报缺'),
            (0, u'取消'),
            )

    # tracking = models.CharField(max_length=250, default="", blank=True, verbose_name=u"运单号")#暂时没有用去掉
    status = models.IntegerField(default=1, choices=STATUS, verbose_name=u"处理状态")
    action_status = models.IntegerField(default=0, choices=ACTION_STATUS, verbose_name=u"对单状态")
    in_status = models.IntegerField(default=0, choices=IN_STATUS, verbose_name=u"入库状态")
    purchaseorder = models.ForeignKey(PurchaseOrder, blank=True, null=True, verbose_name=u"采购单id")
    item = models.ForeignKey(product.models.Item, verbose_name=u"item_id")
    qty = models.IntegerField(default=0, verbose_name=u"采购数量")
    cost = models.FloatField(default=0, verbose_name=u"采购单价")

supply/templates/create_purchaseorder.html
{% extends "base_header.html" %}
{% block content %}

<div class="alert alert-warning alert-dismissable">
    <strong style="font-size:20px;">
        1、一键生成采购单的来源是包含2个点：a、开始处理的采购方案下的货品；b、无库存的订单货品<br>
    </strong>
</div>

 <form class="form-inline" role="form" id="create_purchaseorder" action="#" method="post" style="float:left;">
    {% csrf_token %}
    <input type="hidden" name="type" value="create_purchaseorder">
    <div>
    <button style="font-size:40px;width:300px; height:70px;margin-bottom:30px;" type="submit" class="btn btn-default btn-primary" >一键生成采购单</button>
    </div>
</form>
<br>


<script type="text/javascript">

</script>
{% endblock %}

supply/templates/purchaseorderitem_check.html
{% extends "base_header.html" %}
{% load tags %}
{% block content %}

{% if success %}
    <div class="alert alert-warning alert-dismissable">
        <strong style="font-size:20px;">{{ msg }}</strong>
    </div>
{% endif %}

<!-- 这里是搜索模板 -->
{% include "purchaseordersearch.html" %}

<br>
<form class="form-inline" role="form" id="uform" action="{{ request.path }}" method="post">
    {% csrf_token %}
    <input type="hidden" id="type" name="type" value="do_check">
    <!--<input type="hidden" id="checkorder_receive" name="checkorder_receive" value="">-->
    <button type="button" class="btn btn-primary" id="package_click">确认对单</button>

    <button type="button" class="btn btn-primary" id="export_csv" style="float: right;">导出对单</button>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th><input type="checkbox" id="checkall">采购产品ID </th>
                <th>采购单ID</th>
                <th>item-SKU</th>
                <th>尺码</th>
                <th>入库仓库</th>
                <th>图片</th>
                <th>采购数量</th>
                <th>已入库数量</th>
                <th>已对单数量</th>
                <th>当前对单数量</th>
                <th>采购单生成时间</th>
                <th>采购单状态</th>
                <th>采购条目处理状态</th>
                <th>采购条目对单状态</th>
                <th>采购条目入库状态</th>
                <th>重量</th>
                <th>供应商</th>
                <th>供应商sku</th>
                <th>国内物流号</th>
                <th>备注</th>
                <th>单据录入人</th>
                <th>采购人</th>
                <th>对单记录</th>
                <th>最后修改时间</th>
                <th>残次记录</th>
            </tr>
        </thead>
        <tbody>
        {% for obj in info %}
        <tr>
            <td><input type="checkbox" name="purchase_item_id" value="{{ obj.id }}"><a href="/admin/supply/purchaseorderitem/{{ obj.id }}">{{ obj.id }}</a> </td>
            <td><a href="/admin/supply/purchaseorder/{{ obj.purchaseorder.id }}">{{ obj.purchaseorder.id }}</a></td>
            <td><a href="{{ obj.item.product.choies_site_url }}" target="_blank">{{ obj.item.sku }}</a></td>
            <td>{{ obj.item_size}}</td>
            <td>{{ obj.purchaseorder.depot }}</td>
            <td><a href="{{ obj.item.product.get_image }}" target="_blank"><img src="{{ obj.item.product.get_image }}" ></a></td>
            <td>{{ obj.qty }}</td>
            <td>{{ obj.depotinlog_qty }}</td>
            <td>{{ obj.real_qty }}</td>
            <td><input class="current_real_qty" value="0" type="text" id="current_real_qty_{{ obj.id }}" style="width:60px;"></td>
            <td>{{ obj.purchaseorder.created|date:"Y-m-d" }}</td>
            <td>{{ obj.purchaseorder.get_status_display }}</td>
            <td>{{ obj.get_status_display }}</td>
            <td>{{ obj.get_action_status_display }}</td>
            <td>{{ obj.get_in_status_display}}</td>


            <td>
                <input disabled class="weight" value="{{ obj.item.weight }}" type="text" id="weight_{{ obj.item.id }}" style="width:60px;">
                <a class="btn btn-default btn111" id="btn_{{ obj.item.id }}" href="javascript:update_weight('{{ obj.item.id }}','{{ obj.item.weight }}','{{ obj.item.sku }}')">更新</a>
            </td>
            <td>{{ obj.purchaseorder.supplier }}</td>
            <td>{{ obj.supplier_sku }}</td>
            <td>
                <p type="text" id="trackingNo_{{ obj.purchaseorder.id }}" class="trackingNo_{{ obj.purchaseorder.id }}" style="width:120px;">{{ obj.purchaseorder.tracking }}</p>
                <a class="btn btn-default" href="javascript:update_poi_trackingNo({{ obj.purchaseorder.id }})">更新</a>
            </td>
            <td>{{ obj.note }}</td>
            <td>{{ obj.purchaseorder.creater }}</td>
            <td>{{ obj.purchaseorder.manager }}</td>
            <td><a class="btn btn-default" href="/admin/supply/purchaseordercheckeditem/?purchaseorderitem__exact={{ obj.id }}" target="_blank">已对单明细</a>
                <br><br>
            <!--<a class="btn btn-default" href="/admin/depot/depotinlog/?content_type__exact=50&object_id=0">已入库明细</a></td>-->
            <td>{{ obj.purchaseorder.updated|date:"Y-m-d" }}</td>
            <td><a class="btn btn-default" href="/admin/supply/purchaseorderqualitytesting/?purchaseorderitem__exact={{ obj.id }}" target="_blank">已记录的残次</a>
                <br><br>
                <a class="btn btn-default" href="/admin/supply/purchaseorder/{{ obj.purchaseorder.id }}">登记残次</a>
                <br><br>
                <!--<a class="btn btn-default" href="http://192.168.11.40:8003/tongguan/print_barcode/?depotitem_id={{ obj.depotitem_id }}&qty=1">不带水洗标打印条码</a>-->
                <a class="btn btn-default" href="{% url 'print_barcode' %}?depotitem_id={{ obj.depotitem_id }}&qty={{ obj.real_qty }}&wash_mark=0" target="_blank">不带水洗标打印条码</a>
                <br><br>
                <a class="btn btn-default" href="{% url 'print_barcode' %}?depotitem_id={{ obj.depotitem_id }}&qty={{ obj.real_qty }}&wash_mark=1" target="_blank">带水洗标打印条码</a>
            </td>

            <!--<td>-->
                <!--{% if obj.checked %}-->
                <!--<button type="button" class="btn btn-default" onclick="javascript:window.open('/purchaseorder/printBarcode/{{ obj.id }}')" >html条码</button>-->
                <!--{% endif %}-->
            <!--</td>-->
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <!--<button type="button" class="btn btn-primary" id="package_click">确认对单</button>-->

</form>
<br>

{% digg_paginator info %}


<script type="text/javascript">

    //初始化模态框内容
    $(".item_report_equal").click(function(){
        var itemId = $(this).attr("id");
        $("#ajax_itemId").val(itemId);
        $("#ajax_time").val("");
        $("#ajax_note").val("");
    });


    $(document).ready(function(){

        $("#tracking").focus();
        $("#checkall").click(function(){
            if($("#checkall").attr('checked')){
                $("input[name='purchase_item_id']").attr("checked",true);
            }else{
                $("input[name='purchase_item_id']").attr("checked",false);
            }
        })

        $('.date').datepicker({
            'dateFormat': 'yy-mm-dd'
        });

        $("#package_click").click(function(){
            var array= new Array();
            $("input[name='purchase_item_id']").each(function(){

                if($(this).attr("checked")){
                    str = $(this).val()+'#'+$("#current_real_qty_"+$(this).val()).val()
                    array.push(str)
                    console.log(str)

                }
             });
           if(array.length==0){
                alert("请选择采购条目后再提交确认对单")
           }else{
                console.log(array.join(','))
                array_str = array.join(',')
                $.post(
                    '/supply/supplier/ajax_update_checkorder_num',
                    {"pois":array_str},
                    function (data) {
                        if(!data["status"]){
                            alert(data["msg"]);
                        }else{
                            location.href=data['path'];
                        }
                    },
                    'json'
                    )
                }
         });
    });


    $("#export_csv").click(function(){
        $("#type").val("export_csv")
        $("#uform").submit()
    });


    $("button[name='checkorder_receive']").each(function(){
        $(this).click(function(){
            var weight = $(this).parent().parent().find($('.weight')).val()
            if( weight == undefined || weight == 0 ){
                alert('产品重量为0, 请更新产品的重量');
            }else{
                //$("#type").val("checkorder_receive")
                //$("#checkorder_receive").val($(this).val())
                //$("#uform").submit()
                console.log($(this).val())
            }
        })
    });

    // 更新poi运单号
    function update_poi_trackingNo(poiId){

        var rea = window.prompt("物流号(多个物流用，请用英文字符,分隔)：");
        if( rea != null )
        {
            $.post(
                '/supply/supplier/ajax_update_poi_trackingNo',
                {"poiId":poiId, "trackingNo":rea},
                function (data) {
                    if(data["status"]){
                        $('.trackingNo_'+poiId).html(rea);
                    }else{
                        alert(data["message"]);
                    }
                },
                'json'
            )
        }
    };

    // 更新重量
    function update_weight(id,old_weight,model){
        console.log(id,old_weight,model)
        var rea = window.prompt(model+"产品重量：");
        var weight = $('#weight_'+id).val()
        console.log(rea,weight)
        if(typeof(rea) == "undefined" || rea=='' || isNaN(rea)){
                alert("请填写数字重量")
                return false
        }else{
            $.post(
                '/supply/supplier/ajax_item_weight',
                {id:id,weight:rea,model:model,},
                function (data) {
                    if (data){
                        // alert("修改成功!")
                        $('#weight_'+id).val(rea)
                        $('#btn_'+id).attr('onclick',"javascript:update_weight('"+id+"','"+rea+"','"+model+"')")
                    }else{
                        // alert("修改失败!")
                        //$('#weight_'+id).val(old_weight)
                        alert("修改产品重量失败")
                    }
                },
                'json'
            )
        }
    }
</script>

{% endblock %}